### ISSUE TITLE
False PP Values being assigned

### ISSUE THREAD

**Issue by Mattsassin** [halsafar/BeatSaberSongBrowser#14]
When sorting via PP, a number of different versions of Freedom Dive will appear at the top. Of course, only one of them is ranked, but each of them display the same PP value when clicked on.

**Comment by halsafar** [comment]
I'm going to guess that you manually unzip your downloaded songs and do not use versioned song folders.  If you download from BeatDrop or BeatSaberDownloader you will end up with versioned song folders.

If you are using versioned song folders it looks like this: `BeatSaber_Install/CustomSongs/3037-2154/Freedom Dive`.

If you are not and just unzipped directly into your `CustomSongs` folder, then you end up with: `BeatSaber_Install/CustomSongs/Freedom Dive`.

If you are not using versioned song folders SongBrowserPlugin falls back to using the Song Name to match PP.  Song Name is not guaranteed unique.  This leads to the bug you have run into.

There really isn't a fix since custom songs don't know their own version.  There is no way to match them.  

The custom song community has to fix the fact that songs don't know their own version.  Until then either start using BeatDrop/BeatSaberDownloader or live with the fact the matching is poor since names are not unique.

**Comment by Mattsassin** [comment]
My song folders _are_ versioned though, and the folders are formatted as you said, and this bug still occurs- all my songs were downloaded via BeatDrop.

**Comment by Mattsassin** [comment]
Worked today, despite no change.

**Comment by halsafar** [comment]
First, apologies for my "guess" followed up by a wall of text.  So far all those who had this issue they resolved it by switching to versioned folders.

Second, there is a bug here.  I was able reproduce something similar.  I was actually typing up a response when you closed this 😄 

Once I have reproduction steps I'll probably re-open this.

Until then, glad it is working for you now!
