### ISSUE TITLE
Request: Minimize the UI

### ISSUE THREAD

**Issue by Vogeluff** [halsafar/BeatSaberSongBrowser#148]
i have a simple request that isn't necessary.. but i would love it haha :D

i basically would suggest some sort of minimization of the UI, not by redesigning or whatever, but through some sort of colapsing into a single symbole. hope you understand what i mean. basically have the whole ui be only a single button until you click (or hover) that, which will roll out the full thing and then, after you did your sorting, hide it again in the single button. 

would love the minimalistic aspect.

also, similar reasoning: an option to hide the "songs loaded" and songbrowser version text that appears ever so often.

thanks for the great work!! :) really appreciated

**Comment by halsafar** [comment]
Apologies for the late response on this.  This is partially the direction SongBrowser will need to go as the UI cannot expand much more.  Currently working on refactoring the filtering UI to similar to what you are requesting.  

The last SongBrowser update should have fixed it so that message only shows up once and only hangs around for a few seconds.  That songs loaded spam was not intentional.  

Glad you are enjoying!  Always happy to take requests.  I'll post back here when I've updated the filtering UI but I'm going to close this for now.
