### ISSUE TITLE
When using any sort mode, sort reverts to alphabetical after finishing a level 

### ISSUE THREAD

**Issue by nge6427** [halsafar/BeatSaberSongBrowser#59]
Occasionally after finishing a level, the song list will be sorted alphabetically while the previously selected sort mode is still selected. Might take several attempts to reproduce.

**Comment by Moletrix** [comment]
Same problem.

**Comment by Mace404** [comment]
It only (and always) happens when after completing a song and the score screen is shown. (practise or normal play doesnt matter)
When you then go back to menu, the sorting is reset to default.

When afterr a song- on the score screen, press restart and then pause the song and go back to menu - the sorting is not reset.

**Comment by TheTotemizer** [comment]
Complete a song -> Sorting reverts to alphabetical
Fail a song -> Sorting reverts to alphabetical
Exit to songlist during song -> Sorting remains as it was

**Comment by shrubin** [comment]
From a cursory glance, it appears what's happening is that SetCurrentLevelPack is getting called from the continueButtonPressedEvent, where it claims to "reset all packs just in case". The problem is that ResetLevelPacks reloads the levels, clearing all sorting.

I believe one possible solution would be to call _model.ProcessSongList and RefreshSongList [right after calling UpdateLevelPackSelection and before the SelectAndScrollToLevel](https://github.com/halsafar/BeatSaberSongBrowser/blob/332e4dc35af90719eb79f595601e1d0f9a455273/SongBrowserPlugin/UI/Browser/SongBrowserUI.cs#L576). As long as nothing is resetting the sort mode, this should re-sort the songs after pressing continue. Alternatively, just don't call ResetLevelPacks if that isn't necessary.

If somebody could try this out or point me to dev setup instructions, that would be great.

**Comment by nge6427** [comment]
@shrubin I just committed and was testing the same fix. https://github.com/nge6427/BeatSaberSongBrowser/commit/40cca19db6d1dbc89b89570527eaa613ce74c731

Can confirm it works.

**Comment by halsafar** [comment]
Sorry for the delay on getting a release out.  I was traveling and away from a computer.

Released 3.0.6 with the fix.  Thanks everyone!
