### ISSUE TITLE
Sorting by PP not available due to empty "BeatStar" json file.

### ISSUE THREAD

**Issue by L1Z1X** [halsafar/BeatSaberSongBrowser#78]
It looks like pp information was previously being loaded from [this endpoint](https://wes.ams3.cdn.digitaloceanspaces.com/beatstar/bssb.json) which is now returns an empty json response.

This isn't the first time there's been an issue with the PP json file.  I wonder if it would be possible to cache the last known good response from the endpoint to use as a fallback?

**Comment by WesVleuten** [comment]
Hi there, I maintain the BeatStar project which includes the pp sorting of the songbrowser.

The reason why that endpoint is now empty is because it relied on the old beatsaver key. As seen in [this commit ](https://github.com/halsafar/BeatSaberSongBrowser/commit/b1e0d8587a67a5526e52265c6ae8143037e6406b) we have a new url which is better optimized (and also allows for sorting by star rating).

I'm looking at better backwards compatibility. That should be done within a couple days.

**Comment by L1Z1X** [comment]
Ah great.  Thanks!

Resolved in #77

**Comment by halsafar** [comment]
Just to chime in.  
Hoping to release an update today with this fixed.
