### ISSUE TITLE
SongBrowser does not start properly

### ISSUE THREAD

**Issue by qlulezz** [halsafar/BeatSaberSongBrowser#99]
So after reinstalling the Plugin(s) and the game, I don't know how to fix this issue:
After checking the Console to see, what was going on, I saw, that SongBrowser was detected and fully functional, but then I scrolled down and saw this.
![SongBrowser-NotWorking](https://user-images.githubusercontent.com/54777265/71637367-c7837900-2c41-11ea-91ee-23a754901b16.JPG)
I saw, that there was an invalid character [&], so I removed it. Then the console showed this (note that the invalid character warning is now gone):
![Problem2](https://user-images.githubusercontent.com/54777265/71637429-7d02fc00-2c43-11ea-94f8-6d541f728866.JPG)

**Comment by qlulezz** [comment]
It somehow fixed itself after reinstalling all of the Libraries.

**Comment by halsafar** [comment]
Glad to hear.  I was positive I fixed that in SongBrowser 6.0.2 released yesterday.  If it happens again feel free to re-open this.  Originally this bug was caused if you restored the file "Playlists/SongBrowserFavorites.json" but also had the migrated file, "Playlists/SongBrowserFavoritesMigrated.json".
